# Generated by Django 5.2.2 on 2025-06-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('fname', models.CharField(max_length=35)),
                ('mname', models.CharField(max_length=35)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=35)),
            ],
        ),
    ]
