# Generated by Django 5.2.2 on 2025-06-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
                ('utype', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
