# Generated by Django 5.2.2 on 2025-06-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('contactno', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('enquirytext', models.CharField(max_length=255)),
                ('enquirydate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
