# Generated by Django 5.2.2 on 2025-06-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('ntitle', models.CharField(max_length=20)),
                ('ndesc', models.CharField(max_length=200)),
                ('ndate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
