# Generated by Django 5.2.2 on 2025-06-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('pdate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
