# Generated by Django 5.2.2 on 2025-06-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=50)),
                ('bdate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
