# Generated by Django 5.2.2 on 2025-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('yid', models.AutoField(primary_key=True, serialize=False)),
                ('yname', models.CharField(max_length=50)),
                ('ydate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
