# Generated by Django 5.2.2 on 2025-06-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('my_file', models.FileField(upload_to='material/')),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
