# Generated by Django 5.2.2 on 2025-06-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fdesc', models.CharField(max_length=200)),
            ],
        ),
    ]
