# Generated by Django 5.2.2 on 2025-06-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roll_no', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('restype', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('responsetext', models.CharField(max_length=1000)),
                ('responsedate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
