# Generated by Django 5.2.2 on 2025-07-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('que', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=30)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
